<?php

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit; // Direct access not allowed
}

/**
 * Genisoft Security Connector admin settings page.
 *
 * Lets the WordPress administrator paste the API key generated by the SaaS dashboard.
 * Available under: Settings → Genisoft Security
 */
class GENISECO_Admin_Settings
{
    private const OPTION_KEY      = 'geniseco_hmac_secret';
    private const MENU_SLUG       = 'genisoft-security-connector';
    private const SETTINGS_GROUP  = 'geniseco_settings_group';

    public function __construct()
    {
        add_action('admin_menu', [$this, 'add_settings_page']);
        add_action('admin_init', [$this, 'register_settings']);
    }

    public function add_settings_page(): void
    {
        add_options_page(
            __('Genisoft Security Connector', 'genisoft-security-connector'),
            __('Genisoft Security', 'genisoft-security-connector'),
            'manage_options',
            self::MENU_SLUG,
            [$this, 'render_page'],
        );
    }

    public function register_settings(): void
    {
        register_setting(self::SETTINGS_GROUP, self::OPTION_KEY, [
            'type'              => 'string',
            'sanitize_callback' => [$this, 'sanitize_api_key'],
            'default'           => '',
        ]);

        add_settings_section(
            'geniseco_main_section',
            __('Connection settings', 'genisoft-security-connector'),
            fn() => null,
            self::MENU_SLUG,
        );

        add_settings_field(
            'geniseco_hmac_secret_field',
            __('API key', 'genisoft-security-connector'),
            [$this, 'render_api_key_field'],
            self::MENU_SLUG,
            'geniseco_main_section',
        );
    }

    public function sanitize_api_key(mixed $value): string
    {
        $sanitized = sanitize_text_field((string) $value);
        // The key must be 64 hexadecimal characters (32 bytes).
        if (!empty($sanitized) && !preg_match('/^[0-9a-f]{64}$/', $sanitized)) {
            add_settings_error(
                self::OPTION_KEY,
                'geniseco_invalid_key',
                __('The API key must be 64 hexadecimal characters. Copy it from your WP Security dashboard.', 'genisoft-security-connector'),
                'error'
            );
            return (string) get_option(self::OPTION_KEY, '');
        }
        return $sanitized;
    }

    public function render_api_key_field(): void
    {
        $value = (string) get_option(self::OPTION_KEY, '');
        $is_configured = !empty($value);
        ?>
        <input
            type="password"
            id="geniseco_hmac_secret"
            name="<?php echo esc_attr(self::OPTION_KEY); ?>"
            value="<?php echo esc_attr($value); ?>"
            class="regular-text"
            autocomplete="off"
            placeholder="<?php echo esc_attr__('Paste your API key from the dashboard here', 'genisoft-security-connector'); ?>"
        />
        <p class="description">
            <?php if ($is_configured) : ?>
                <span style="color: #00a32a"><?php echo esc_html__('API key configured.', 'genisoft-security-connector'); ?></span>
                <?php echo esc_html__('You can replace it by entering a new value.', 'genisoft-security-connector'); ?>
            <?php else : ?>
                <?php echo esc_html__('Find your API key in the', 'genisoft-security-connector'); ?>
                <a href="https://wordpress.genisoft.fr/sites/new" target="_blank" rel="noopener noreferrer"><?php echo esc_html__('WP Security dashboard', 'genisoft-security-connector'); ?></a> →
                <strong><?php echo esc_html__('Sites → Add a site', 'genisoft-security-connector'); ?></strong>.
            <?php endif; ?>
        </p>
        <?php
    }

    public function render_page(): void
    {
        if (!current_user_can('manage_options')) {
            wp_die(esc_html__('Access denied.', 'genisoft-security-connector'));
        }

        $is_configured = !empty(get_option(self::OPTION_KEY, ''));
        ?>
        <div class="wrap">
            <h1>
                <span style="display:inline-flex;align-items:center;gap:8px">
                    <svg width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="#2563eb" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z"/>
                    </svg>
                    <?php echo esc_html__('Genisoft Security Connector', 'genisoft-security-connector'); ?>
                </span>
            </h1>

            <p><?php echo esc_html__('Plugin version:', 'genisoft-security-connector'); ?> <strong><?php echo esc_html(GENISECO_VERSION); ?></strong></p>

            <?php if ($is_configured) : ?>
                <div class="notice notice-success is-dismissible">
                    <p>
                        <strong><?php echo esc_html__('Plugin connected.', 'genisoft-security-connector'); ?></strong> <?php echo esc_html__('Your site is monitored by WP Security.', 'genisoft-security-connector'); ?>
                        <a href="https://wordpress.genisoft.fr" target="_blank" rel="noopener noreferrer"><?php echo esc_html__('Open the dashboard →', 'genisoft-security-connector'); ?></a>
                    </p>
                </div>
            <?php else : ?>
                <div class="notice notice-warning">
                    <p>
                        <strong><?php echo esc_html__('Plugin not configured.', 'genisoft-security-connector'); ?></strong>
                        <?php echo esc_html__('Enter your API key below to start monitoring this site.', 'genisoft-security-connector'); ?>
                    </p>
                </div>
            <?php endif; ?>

            <form method="post" action="options.php">
                <?php
                settings_fields(self::SETTINGS_GROUP);
                do_settings_sections(self::MENU_SLUG);
                submit_button(__('Save API key', 'genisoft-security-connector'));
                ?>
            </form>

            <hr>
            <h2><?php echo esc_html__('System information', 'genisoft-security-connector'); ?></h2>
            <table class="widefat striped" style="max-width:500px">
                <tbody>
                    <?php
                    $infos = [
                        'WordPress' => get_bloginfo('version'),
                        'PHP'       => PHP_VERSION,
                        __('Site URL', 'genisoft-security-connector')    => get_site_url(),
                        __('HMAC status', 'genisoft-security-connector') => $is_configured
                            ? __('Configured', 'genisoft-security-connector')
                            : __('Not configured', 'genisoft-security-connector'),
                    ];
                    foreach ($infos as $label => $value) {
                        echo '<tr><th>' . esc_html($label) . '</th><td>' . esc_html($value) . '</td></tr>';
                    }
                    ?>
                </tbody>
            </table>
        </div>
        <?php
    }
}
